import socket, struct

class GPIOClass:
	#DEFINITIONS ON HOW TO SET THE GPIO OUT IN ORDER TO IRRIGATE
	#STATE_ON MEANS IRRIGATING, AND IS HOW GPIO NEEDS TO BE SET UP TO IRRIGATE
	#MOST TIME 1=HIGH AND RELAY=CLOSE -> IRRIGATING
	#SOMETIMES IN ORDER TO CLOSE THE RELAY YOU NEED TO SET IT UP AS 0

	STATE_ON = 0
	STATE_OFF = 1

	def __init__(self):

		pass
	def openWater(self, pin):
		pass
	def closeWater(self, pin):
		pass
